accounts/urls.py
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView

app_name = "accounts"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout-view"),
]

hacogi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("events.urls", namespace="events")),
    path("", include("contact.urls")),
    path("", include("team.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

team/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("team/", views.team_page, name="team"),
    path("support/", views.support_page, name="support"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("destinations/", views.destinations_list, name="destinations"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from accounts.managers import CustomUserManager
from events.models import IdeaUpvote


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email address"), unique=True)

    first_name = models.CharField(_("first name"), max_length=150)
    last_name = models.CharField(_("last name"), max_length=150)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = CustomUserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def likes_idea(self, idea_id):
        return IdeaUpvote.objects.filter(user=self, idea_id=idea_id)

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.forms import TextInput, EmailInput, PasswordInput
from accounts.models import CustomUser


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Username'
        })
        self.fields['password'].widget = PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Password'
        })

class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Email'
        })
        self.fields['password1'].widget = PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Password',
            'id': 'password1'
        })
        self.fields['password2'].widget = PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Your Password Confirmation',
            'id': 'password2'
        })

    class Meta:
        model = CustomUser
        fields = (
            "email",
            "password1",
            "password2"
        )

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View

from accounts.forms import CustomLoginForm, RegisterForm


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "accounts/register.html", context={"form": form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
        return render(request, "accounts/register.html", context={"form": form})


class LoginView(View):
    def get(self, request):
        form = CustomLoginForm()
        return render(request, "accounts/login.html", context={"form": form})

    def post(self, request):
        form = CustomLoginForm(request, request.POST)

        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                return redirect("events:home")

        return render(request, "accounts/login.html", context={"form": form})


def logout_view(request):
    logout(request)
    return redirect("events:home")

accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!-- Icon title -->
    <link
      rel="shortcut icon"
      href="{% static 'images/logo.png' %}"
      type="image/x-icon"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Login Page{% endblock title %}</title>
    <!-- splide JS -->
    <link
      href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css"
      rel="stylesheet"
    />
    <!-- bootstrap css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <!-- Font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <!--  -->
  <body>
    <div
      class="container d-flex justify-content-center align-items-center mt-4"
    >
      <div
        class="p-5 shadow-lg w-100"
        style="
          max-width: 400px;
          border-radius: 15px;
          background-color: var(--white);
        "
      >
        <h2 class="text-center mb-4 tt tt-bold">Login</h2>
        <form method="POST" class="needs-validation" novalidate>
          {% csrf_token %} {% if form.non_field_errors %}
          <div class="alert alert-danger">
            {% for error in form.non_field_errors %} {{ error }} {% endfor %}
          </div>
          {% endif %} {% for field in form %}
          <div class="form-group mb-3">
            <label
              for="{{ field.id_for_label }}"
              class="form-label fw-bold"
              style="color: var(--primary_blue)"
            >
              {{ field.label }}
            </label>
            {{ field }} {% if field.errors %}
            <div class="text-danger ds mt-1">
              {% for error in field.errors %}
              <small class="ds">{{ error }}</small>
              {% endfor %}
            </div>
            {% endif %}
          </div>
          {% endfor %}

          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-lg btn-login">Login</button>
          </div>
        </form>

        <p class="text-center mt-3">
          <a
            href="{% url 'accounts:register' %}"
            class="ds text-decoration-none"
          >
            Don't have an account? Sign up
          </a>
        </p>
      </div>
    </div>
    <!-- splide JS -->
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <!-- bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <!-- Custom JS -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!-- Icon title -->
    <link
      rel="shortcut icon"
      href="{% static 'images/logo.png' %}"
      type="image/x-icon"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Register Page{% endblock title %}</title>
    <!-- splide JS -->
    <link
      href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css"
      rel="stylesheet"
    />
    <!-- bootstrap css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <!-- Font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>

  <!--  -->
  <body>
    <div class="container">
      <div class="text-center d-flex justify-content-center align-items-center">
        <h1 class="tt tt-bold text-center">Create an Account</h1>
      </div>
      <div class="d-flex justify-content-center align-items-center">
        <div
          class="p-5 shadow-lg w-100"
          style="
            max-width: 500px;
            border-radius: 15px;
            background-color: var(--white);
          "
        >
          <form method="POST" class="needs-validation" novalidate>
            {% csrf_token %}

            <div class="form-group mb-3">
              <label
                for="id_email"
                class="form-label fw-bold"
                style="color: var(--primary_blue)"
                >Email address:</label
              >
              {{ form.email }}
            </div>

            <div class="form-group mb-3">
              <label
                for="id_password1"
                class="form-label fw-bold"
                style="color: var(--primary_blue)"
                >Password:</label
              >
              {{ form.password1 }}
            </div>

            <div class="form-group mb-3">
              <label
                for="id_password2"
                class="form-label fw-bold"
                style="color: var(--primary_blue)"
                >Password confirmation:</label
              >
              {{ form.password2 }}
            </div>

            <div class="form-group mb-4">
              {{ form.password_based_authentication }}
            </div>

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-register btn-lg">
                Sign Up
              </button>
            </div>

            <p class="text-center mt-3">
              <a
                href="{% url 'accounts:login' %}"
                class="text-secondary text-decoration-none"
                >Already have an account? Log in</a
              >
            </p>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>