accounts/urls.py
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView

app_name = "accounts"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout-view"),
]

events/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "events"

urlpatterns = [
    path("", views.home_page, name="home"),
    path(
        "<int:event_id>/",
        EventDetailView.as_view(),
        name="event-detail",
    ),
    path(
        "<int:event_id>/ideas/",
        CreateEventIdeaView.as_view(),
        name="create-idea",
    ),
    path(
        "<int:event_id>/ideas/<int:idea_id>",
        UpvoteIdeaView.as_view(),
        name="upvote-idea",
    ),
    path(
        "event/<int:event_id>/idea/<int:idea_id>/upvote/",
        views.UpvoteIdeaView.as_view(),
        name="upvote-idea",
    ),
    path(
        "idea/<int:idea_id>/delete/",
        DeleteIdeaView.as_view(),
        name="delete-idea",
    ),
]

hacogi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("events.urls", namespace="events")),
    path("", include("contact.urls")),
    path("", include("team.urls")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

team/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("team/", views.team_page, name="team"),
    path("support/", views.support_page, name="support"),
    path("privacy-policy/", views.privacy_policy, name="privacy_policy"),
    path("destinations/", views.destinations_list, name="destinations"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!-- Icon title -->
    <link
      rel="shortcut icon"
      href="{% static 'images/logo.png' %}"
      type="image/x-icon"
    />
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    <!-- splide JS -->
    <link
      href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css"
      rel="stylesheet"
    />
    <!-- bootstrap css -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <!-- Font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <!-- HEADER start -->
    <div id="active"></div>
    <header class="header">
      <div class="container">
        <div class="row header__row">
          <div class="col-6 col-lg-3 header__logo">
            <a href="{% url 'events:home' %}">
              <img
                class="header__logo"
                src="{% static 'images/logo.png' %}"
                alt="Logo"
              />
            </a>
          </div>

          <div class="col-6 header__menu">
            <ul>
              <li>
                <a
                  onclick="addOpen()"
                  href="{% url 'events:home' %}"
                  aria-disabled="true"
                  class="{% if request.path == '/' %}active {% endif %}"
                  >Home
                </a>
              </li>
              <li>
                <a onclick="addOpen()" href="{% url 'events:home' %}#active"
                  >Active</a
                >
              </li>
              <li>
                <a onclick="addOpen()" href="{% url 'events:home' %}#upcoming"
                  >Upcoming</a
                >
              </li>
              <li>
                <a onclick="addOpen()" href="{% url 'events:home' %}#past"
                  >Past</a
                >
              </li>
            </ul>

            <i
              class="d-block d-lg-none fa-solid fa-xmark header__close"
              onclick="addOpen()"
            ></i>
          </div>

          <!--  -->
          <div class="col-6 col-lg-3 header__iconBox dropdown">
            <button
              class="btn dropdown-toggle btn__account"
              type="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <i class="fa-regular fa-user"></i>
              <span class="d-none d-md-block header__iconBox__btn"
                >My Account</span
              >
            </button>
            <ul class="dropdown-menu dropdown-menu_me">
              <li>
                <div>
                  {% if user.is_authenticated %}
                  <a
                    class="btn btn-outline-danger dropdown-item btn_out"
                    href="{% url 'accounts:logout-view' %}"
                  >
                    <span
                      ><i class="fa-solid fa-user-slash me-3"></i>Logout</span
                    >
                  </a>
                  {% else %}
                </div>
              </li>
              <li>
                <div>
                  <a
                    class="btn btn-outline-light dropdown-item btn_in"
                    href="{% url 'accounts:login' %}"
                  >
                    <span><i class="fa-solid fa-user me-3"></i>Login</span>
                  </a>
                  {% endif %}
                </div>
              </li>

              <li>
                <div>
                  <a
                    href="{% url 'accounts:register'%}"
                    class="btn btn-warning dropdown-item btn_add"
                  >
                    <span>
                      <i class="fa-solid fa-user-plus me-3"></i>Sign-up
                    </span>
                  </a>
                </div>
              </li>
              <li><hr class="dropdown-divider" /></li>
            </ul>
            <i
              class="d-block d-lg-none fa-solid fa-bars header__border header__bars"
              onclick="addOpen()"
            >
            </i>
          </div>
          <!--  -->
        </div>
      </div>
    </header>
    <div id="upcoming"></div>

    <!--  -->
    {% block content %}{% endblock content %}

    <!-- ==================== footer start ==================== -->
    {% include "footer.html" %}
    <!-- ==================== footer end ==================== -->

    <!-- splide JS -->
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/js/splide.min.js"></script>
    <!-- bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <!-- Custom JS -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

templates/footer.html
{% load static %}
<!-- ==================== footer start ==================== -->
{% block footer %}
<div class="container">
  <footer class="footer">
    <div class="row">
      <div class="col-12 col-md-6 col-xl-4 footer__contactBox">
        <div class="d-flex justify-content-center">
          <a class="footer__logo" href="{% url 'events:home' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" />
          </a>
        </div>
        <div class="d-flex justify-content-center">
          <p class="ds my-3">Action - is the only way to a result</p>
        </div>
        <ul>
          <li>
            <a href="tel:0123456987">
              <i class="fa-solid fa-phone-volume"></i>
              <span class="ds">+998 99 456 7987</span>
            </a>
          </li>

          <li>
            <a href="https://www.instagram.com/">
              <i class="fa-brands fa-instagram"></i>
              <span class="ds">Hackathons_uz</span>
            </a>
          </li>

          <li>
            <a href="https://www.youtube.com/@Javohir.me.s">
              <i class="fa-brands fa-youtube"></i>
              <span class="ds">Hackogi_uz</span>
            </a>
          </li>
        </ul>
      </div>

      <div class="col-6 col-md-3 col-xl-2 footer__linkBox">
        <h5 class="tt tt-sm my-4 text-center">Quick Links</h5>

        <ul>
          <li><a href="{% url 'about' %}" class="ds">- About Us</a></li>
          <li>
            <a href="{% url 'destinations' %}" class="ds">- Destinations</a>
          </li>
          <li>
            <a href="{% url 'events:home' %}#active" class="ds"
              >- Latest Blog</a
            >
          </li>
          <li><a href="{% url 'team' %}" class="ds">- Our Team</a></li>
          <li><a href="{% url 'contact' %}" class="ds">- Contact Us</a></li>
        </ul>
      </div>

      <div class="col-6 col-md-3 col-xl-2 footer__linkBox">
        <div class="d-flex justify-content-center my-4">
          <h5 class="tt tt-sm">Support</h5>
        </div>
        <ul>
          <li>
            <a href="{% url 'support' %}" class="ds">- Customer Support</a>
          </li>
          <li>
            <a href="{% url 'privacy_policy' %}" class="ds"
              >- Privacy & Policy</a
            >
          </li>
          <li>
            <a href="{% url 'privacy_policy' %}" class="ds"
              >- Terms & Condition</a
            >
          </li>
          <li>
            <a href="{% url 'events:home' %}#participation" class="ds"
              >- Participation</a
            >
          </li>
          <li>
            <a href="{% url 'events:home' %}#organizers" class="ds"
              >- Organizers</a
            >
          </li>
        </ul>
      </div>

      <div
        class="offset-md-2 offset-lg-3 offset-xl-0 col-12 col-md-8 col-lg-6 col-xl-4"
      >
        <div class="d-flex justify-content-center my-4">
          <h5 class="tt tt-sm">Suggestions</h5>
        </div>

        <div class="d-flex justify-content-center mb-4">
          <a class="btn btn_cart" href="{% url 'contact' %}">Contact Us</a>
        </div>
      </div>
    </div>
  </footer>
</div>
{% endblock footer %}
<!-- ==================== footer end ==================== -->

templates/home.html
{% extends "base.html" %} {% load static %}
<!--  -->
{% block title %} Hackogi {% endblock title %}
<!--  -->
{% block content %}
<div class="container">
  <ul>
    <!-- Active Hackathons Section -->
    <h2 class="tt-bold tt-lg">Active Hackathons</h2>
    <div class="container_slider">
      {% if active_hackathons %}
      <section
        id="mySliderActive"
        class="splide"
        aria-label="Active Hackathons"
      >
        <div class="splide__arrows">
          <button class="splide__arrow splide__arrow--prev">
            <i class="fa-solid fa-chevron-left fa-2xl"></i>
          </button>
          <button class="splide__arrow splide__arrow--next">
            <i class="fa-solid fa-chevron-right fa-2xl"></i>
          </button>
        </div>
        <div class="splide__track">
          <ul class="splide__list">
            {% for hackathon in active_hackathons %}
            <li class="splide__slide card">
              <div class="box row">
                <div class="imgBox">
                  <img
                    src="{% if hackathon.image %}{{ hackathon.image.url }}{% else %}{% static 'images/none_image.png' %}{% endif %}"
                    alt="{{ hackathon.title }}"
                  />
                </div>
                <div class="content col-md-6">
                  <h2 class="tt-thin">{{ hackathon.title }}</h2>
                  <a href="{% url 'events:event-detail' hackathon.id %}"
                    >Go somewhere</a
                  >
                </div>
              </div>
              <div class="card-body col-md-6">
                <h5 class="card-title tt-thin">{{ hackathon.title }}</h5>
                <p>{{ hackathon.summary }}</p>
                <a
                  href="{% url 'events:event-detail' hackathon.id %}"
                  class="btn btn_cart"
                  >Go somewhere</a
                >
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </section>
      {% else %}
      <p class="no-hackathons-message ds">
        No active hackathons at the moment.
      </p>
      {% endif %}
    </div>

    <!-- Upcoming Hackathons Section -->
    <div id="past"></div>

    <h2 class="tt-bold tt-lg">Upcoming Hackathons</h2>
    <div class="container_slider">
      {% if upcoming_hackathons %}
      <section
        id="mySliderUpcoming"
        class="splide"
        aria-label="Upcoming Hackathons"
      >
        <div class="splide__arrows">
          <button class="splide__arrow splide__arrow--prev">
            <i class="fa-solid fa-chevron-left fa-2xl"></i>
          </button>
          <button class="splide__arrow splide__arrow--next">
            <i class="fa-solid fa-chevron-right fa-2xl"></i>
          </button>
        </div>
        <div class="splide__track">
          <ul class="splide__list">
            {% for hackathon in upcoming_hackathons %}
            <li class="splide__slide card">
              <div class="box">
                <div class="imgBox">
                  <img
                    src="{% if hackathon.image %}{{ hackathon.image.url }}{% else %}{% static 'images/none_image.png' %}{% endif %}"
                    alt="{{ hackathon.title }}"
                  />
                </div>
                <div class="content">
                  <h2 class="tt-thin">{{ hackathon.title }}</h2>
                  <a href="{% url 'events:event-detail' hackathon.id %}"
                    >Go somewhere</a
                  >
                </div>
              </div>
              <div class="card-body">
                <h5 class="card-title tt-thin">{{ hackathon.title }}</h5>
                <p>{{ hackathon.summary }}</p>
                <a
                  href="{% url 'events:event-detail' hackathon.id %}"
                  class="btn btn_cart"
                  >Go somewhere</a
                >
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
      </section>
      {% else %}
      <p class="no-hackathons-message ds">
        No upcoming hackathons at the moment.
      </p>
      {% endif %}
    </div>

    <!-- Past Hackathons Section -->
    <h2 class="tt-bold tt-lg">Past Hackathons</h2>
    <div class="container_slider">
      <section id="mySliderPast" class="splide" aria-label="Past Hackathons">
        {% if past_hackathons %}
        <div class="splide__arrows">
          <button class="splide__arrow splide__arrow--prev">
            <i class="fa-solid fa-chevron-left fa-2xl"></i>
          </button>
          <button class="splide__arrow splide__arrow--next">
            <i class="fa-solid fa-chevron-right fa-2xl"></i>
          </button>
        </div>
        <div class="splide__track">
          <ul class="splide__list">
            {% for hackathon in past_hackathons %}
            <li class="splide__slide card">
              <div class="box">
                <div class="imgBox">
                  <img
                    src="{% if hackathon.image %}{{ hackathon.image.url }}{% else %}{% static 'images/none_image.png' %}{% endif %}"
                    alt="{{ hackathon.title }}"
                  />
                </div>
                <div class="content">
                  <h2 class="tt-thin">{{ hackathon.title }}</h2>
                  <a href="{% url 'events:event-detail' hackathon.id %}"
                    >Go somewhere</a
                  >
                </div>
              </div>
              <div class="card-body">
                <h5 id="organizers" class="card-title tt-thin">
                  {{ hackathon.title }}
                </h5>
                <p>{{ hackathon.summary }}</p>
                <a
                  href="{% url 'events:event-detail' hackathon.id %}"
                  class="btn btn_cart"
                  >Go somewhere</a
                >
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
        {% else %}
        <p class="no-hackathons-message ds">No past hackathons available.</p>
        {% endif %}
      </section>
    </div>
  </ul>

  <section
    class="wow fadeIn"
    style="visibility: visible; animation-name: fadeIn"
  >
    <div class="container">
      <div class="row justify-content-center">
        <h5 class="tt tt-bold text-center">Organizers</h5>
      </div>
      <div class="row partners-block justify-content-center">
        <img
          class="partner-img m-3 col-12 col-md-6 col-lg-4"
          src="{% static 'images/mohirdev.png' %}"
        />
        <img
          class="partner-img m-3 col-12 col-md-6 col-lg-4"
          src="{% static 'images/tuit.png' %}"
        />
        <img
          id="participation"
          class="partner-img m-3 col-12 col-md-6 col-lg-4"
          src="{% static 'images/itpark.png' %}"
        />
      </div>
    </div>
  </section>

  <!-- ===================================== Participation start ===================================== -->
  <div class="row justify-content-center text-center">
    <h2 class="tt tt-bold text-center">Participation</h2>
    <div
      class="col-12 col-md-6 mb-4 wow fadeInUp"
      style="animation-name: fadeInUp"
    >
      <div class="feature-box p-4 shadow-sm rounded bg-white">
        <div class="icon mb-3">
          <i class="far fa-clock fa-2x"></i>
        </div>
        <p class="ds">
          Full participation in a 72-hour offline hackathon (participants must
          provide themselves with a stable Internet connection).
        </p>
      </div>
    </div>

    <div
      class="col-12 col-md-6 mb-4 wow fadeInUp"
      style="animation-delay: 0.2s; animation-name: fadeInUp"
    >
      <div class="feature-box p-4 shadow-sm rounded bg-white">
        <div class="icon mb-3">
          <i class="fa-brands fa-github fa-2x"></i>
        </div>
        <p class="ds">
          Creation of a digital solution (application, service, device) using
          open data during the event with uploading the code to GitHub.
        </p>
      </div>
    </div>

    <div
      class="col-12 col-md-6 mb-4 wow fadeInUp"
      style="animation-delay: 0.4s; animation-name: fadeInUp"
    >
      <div class="feature-box p-4 shadow-sm rounded bg-white">
        <div class="icon mb-3">
          <i class="fa-solid fa-users fa-2x"></i>
        </div>
        <p class="ds">
          If you participate in a team - your team should consist of no more
          than three participants, and one of the participants must submit a
          team application for participation.
        </p>
      </div>
    </div>
  </div>
  <!-- ===================================== Participation end ===================================== -->
</div>
{% endblock %}

templates/support.html
{% extends 'base.html' %}
<!--  -->
{% block title %} Team {% endblock title %}
<!--  -->
{% load static %} {% block content %}
<section class="conditions">
  <div class="container">
    <div class="row">
      <div class="col">
        <h5 class="tt tt-bold">
          Conditions for participation in the hackathon
        </h5>
      </div>
    </div>
    <div class="row">
      <div class="col col-md-6 fadeInUp">
        <div class="feature-box">
          <i class="far fa-clock"></i>
          <p class="ds">
            Full participation in the 72-hour hackathon in an offline format
          </p>
        </div>
      </div>
      <div class="col col-md-6 fadeInUp delay-1">
        <div class="feature-box">
          <i class="fa-regular fa-window-restore"></i>
          <p class="ds">
            Creation of a digital solution (application, service, device) using
            open data during the hackathon with the code uploaded to GitHub
          </p>
        </div>
      </div>
      <div class="col col-md-6 fadeInUp delay-2">
        <div class="feature-box">
          <i class="fa-solid fa-users"></i>
          <p class="ds">
            When participating in a team - no more than three people and one of
            the participants must submit a team application for participation
          </p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}